import i18n from "i18next";
import { initReactI18next } from "react-i18next";
import LanguageDetector from "i18next-browser-languagedetector";

const resources = {
  kg: {
    translation: {
      main: "Yй",
      aboutUs: "Биз жөнүндө",
      termsOfPurchase: "Сатып алуу шарттары",
      termsOfUse: "Условия соглашения",

      purchase: "Төлөм",
      shipping: "Жеткирүү",
      guarantee: "Кепилдик",
      wholesalers: "Дүң сатуучулар",
      news: "Жаңылыктар",
      contacts: "Байланыштар",
      whatToFind: "Эмне табуу үчүн?",
      addToCart: "Корзинага",
      followТewsletter: "Бюллетенге жазылыңыз!",
      knowFirst:
        "Жаңы жөнүндө биринчилерден болуп билиңиз жарнамалар жана арзандатуулар",
      yourEmail: "Сиздин почта",
      follow: "Жазылуу",
      newItems: "Жаңы",
      inCart: "Арабада",
      hotItems: "Bestsellers",
      paymentMethods: "Төлөм ыкмалары",
      downloadMobileApp: "Мобилдик тиркемени жүктөп алыңыз",
      addToFavorite: "cүйүктүүлөргө кошуу",
      reviews: "сын-пикирлер",
      views: "көрүүлөр",
      share: "Бөлүшүү",
      login: "Кирүү үчүн",
      photoAndVideos: "Сатып алуучулардын сүрөттөрү жана видеолору",
      compilation: "Категория боюнча продуктыларды тандоо",
      recomendations: "Окшош буюмдар",
      description: "Продукт сүрөттөмөсү жана сын-пикирлер",
      profile: "Жеке бөлмө",
      exit: "Чыгуу",
      historyOrders: "Сатып алуу тарыхы",
      historyOperations: "Төлөм тарыхы",
      cart: "Cебет",
      favoriteProducts: "Өзгөчөлөнгөн продуктылар",
      freeCallInKyrg: "Кыргызстандын ичинде чалуу бекер",
      sale: "Сток",
      Bestsellers: "Бестселлер",
      madeWithLove: "Сүйүү менен жасалган",
      selectCategory: "Продукт категориясын тандаңыз",
      selectCity: "Шаарды тандоо",
      priceFrom: "Баштап баасы",
      priceTo: "Чейин баасы",
      show: "Көрсөтүү",
      cancel: "Жокко чыгаруу",
      find: "Товарлар табылды",
      inStock: "Кампада",
      nothingFound: "Эч нерсе табылган жок",
      nothingFoundTxt:
        "Сиздин сурооңуз боюнча эч нерсе табылган жок, башка сөздөр менен дагы издесеңиз болот.",
      centerOffice: "Башкы кеңсе",
      pickupPoint: "Кабыл алуу пункту",
      article: "Сатуучу коду",
      color: "Түс",
      size: "Өлчөм",
      stock: "Жеткиликтүүлүк",
      minimalCount: "Сатып алуу үчүн товарлардын минималдуу саны",
      infoTxt:
        " Соода корзинага каалагандай көп нерселерди кошуп, заказ кылсаңыз болот. Же 'АЗЫР САТЫП АЛ' баскычын чыкылдатуу менен дароо сатып алсаңыз болот.",
      amount: "Cумма",
      buyNow: "Азыр сатып ал",
      questions:
        "Эгерде сизде бул продукт тууралуу суроолоруңуз болсо же TM VISA өнүмдөрүн жапырт сатып алгыңыз келсе, биз менен телефон аркылуу байланышыңыз",
      GeneralInformation: "Жалпы маалымат",
      reviewss: "сын-пикирлер",
      character: "Мүнөздөмөлөрү",
      madeIn: "Өндүрүүчү өлкө",
      stars: "жылдыздар",
      yourComment: "Сиздин пикириңиз",
      txtComment: "Комментарий тексти",
      successComment: "Сиздин комментарий жазыла элек",
      leaveComment: "Комментарий калтырыңыз",
      price: "Баасы",
      total: "Бардыгы",
      choosenProducts: "ТАНДАЛГАН ПРОДУКЦИЯЛАР",
      products: "Товарлар",
      Арзандатуу: "Арзандатуу",
      makeOrder: "Текшерүү",
      country: "ӨЛКӨ",
      city: "ШААР",
      address: "ДАРЕК",
      shipping_method: "Жеткирүү ыкмасы",
      pickUp: "Ала кетүү",
      productsInOrder: "Тартиптеги заттар",
      nothingInCart: "Арабада эч нерсе жок",
      watchInCalalog:
        "Каталогдон өнүмдөрдү таап, аларды корзинага кошсоңуз болот, ошондо сиз аларды тандап, заказ кыла аласыз.",
      fintInCatalog: "Каталогдон өнүмдөрдү табыңыз",
      deleteProduct: "Элемент жок кылынсынбы?",
      deleteProductTxt: "Тандалган өнүм арабага чыгарылсынбы?",
      no: "Жок",
      yes: "Ооба",
      successfullyOrdered: "Заказ ийгиликтүү аяктады",
      successfullyOrderedTxt:
        "Буйрутманы ырастоо, төлөм жана жеткирүү күтүңүз!",
      toMain: "Башкы",
      changePhone: "Телефон номерин өзгөртүү",
      change: "өзгөртүү",
      fromNumber: "Номерден",
      toNumber: "Номерге",
      reg: "Катталуу",
      savee: "Эсте",
      terms: "Мен келишимдин шарттарын кабыл алам",
      forgotPassword: "Паролду унутуп калдыңыз",
      payment: "Төлөө",
      toOrders: "Заказдар боюнча",
      descr: "Сүрөттөмө",
      noneProducts: "Запаста башка буюмдар жок.",
      allOrders: "Жалпы заказдар",
      onSum: "Суммага",
      changeAvatar: "Профиль сүрөтүн өзгөртүү",
      changeProfileData: "Жеке маалыматтарды түзөтүү",
      changePassword: "Сырсөздү өзгөртүү",
      orderDate: "Буйрук датасы",
      shippingDate: "Жеткирүү күнү",
      paymentMethod: "Төлөө ыкмасы",
      shippingMethod: "Жеткирүү ыкмасы",
      productss: "Товарлар",
      newOnesFirst: "Биринчи жаңы",
      oldestFirst: "Эскилер биринчи",
      chepOnesFirst: "Биринчи арзан",
      expensiveFirst: "Биринчи кымбатыраак",
      name: "аты",
      phoneNumber: "ТЕЛЕФОН НОМУРУ",
      save: "Cактоо",
      settings: "Профиль жөндөөлөрү",
      password: "КУПУЯ СӨЗ",
      enterNewPassword: "ЖАҢЫ СӨРДҮ КИРГИЗ",
      repeatNewPassword: "ЖАҢЫ СӨРДҮ КАЙТАЛОО",
      settings1: "профиль орнотуулары",
      default: "Демейки",
      enter: "Кирүү",
      termsFirst: "Мен кабыл алам",
      termsSecond: "макулдашуунун шарттары",
      regg: "Каттоо",
      newPassword: "Сырсөздү калыбына келтирүү",
      newPassword2:
        "Шилтемени чыкылдатуу менен сырсөзүңүздү калыбына келтирүү үчүн биз сизге ырастоо кодун жана телефон номериңизге шилтеме жөнөтөбүз.",
      newPasswordd: "Новый пароль",
      resetPassword: "Сырсөздү кайра коюу",
    },
  },
  ru: {
    translation: {
      main: "Главная",
      aboutUs: "О нас",
      termsOfPurchase: "Условия покупки",
      termsOfUse: "Условия соглашения",
      purchase: "Оплата",
      shipping: "Доставка",
      guarantee: "Гарантия",
      wholesalers: "Оптовикам",
      news: "Новости",
      contacts: "Контакты",
      whatToFind: "Что найти?",
      addToCart: "В корзину",
      followТewsletter: "Подпишитесь на рассылку!",
      knowFirst: "Узнайте первыми о новых акциях и скидках",
      yourEmail: "Ваша почта",
      follow: "Подписаться",
      newItems: "Новинки",
      inCart: "В корзинe",
      hotItems: "Хиты продаж",
      paymentMethods: "Способы оплаты",
      downloadMobileApp: "Скачай мобильное приложение",
      addToFavorite: "добавить в избранное",
      reviews: "отзывов",
      views: "просмотров",
      share: "Поделиться",
      login: "Войти",
      photoAndVideos: "Фото и видео покупателей",
      compilation: "Подборка товаров по категории",
      recomendations: "Похожие товары",
      description: "Описание товара и отзывы",
      profile: "Личный кабинет",
      exit: "Выйти из учётной записи",
      historyOrders: "История заказов",
      historyOperations: "История платежей",
      cart: "Корзина",
      favoriteProducts: "Избранные товары",
      freeCallInKyrg: "Бесплатный звонок по Кыргызстану",
      sale: "Акции",
      Bestsellers: "Хиты продаж",
      madeWithLove: "Сделано с любовью",
      selectCategory: "Выберите категорию товаров",
      selectCity: "Выберите город",
      priceFrom: "Цена от",
      priceTo: "Цена до",
      show: "Показать",
      cancel: "Отмена",
      find: "Товаров найдено",
      inStock: "В наличии",
      nothingFound: "Ничего не найдено",
      nothingFoundTxt:
        "По вашему запросу ничего не найдено, вы можете повторить поиск с другими словами.",
      centerOffice: "Центральный офис",
      pickupPoint: "Пункт получения товара",
      article: "Артикул",
      color: "Цвет",
      size: "Размер",
      stock: "Наличие",
      minimalCount: "Минимальное количество к продаже",
      infoTxt:
        "Вы можете добавить в корзину нужное количество товаров и после оформить заказ. Или вы купить сразу нажав на кнопку “КУПИТЬ СЕЙЧАС”.",
      amount: "количество",
      buyNow: "Купить сейчас",
      questions:
        "Если у вас возникли вопросы об этом товаре или вы желаете купить продукцию ТМ VISA оптом, свяжитесь с нами по телефонам",
      GeneralInformation: "Общая информация",
      reviewss: "Отзывы",
      character: "Характеристики",
      madeIn: "Страна-изготовитель",
      stars: "звезд",
      yourComment: "Ваш комментарий",
      txtComment: "Текст комментария",
      leaveComment: "Оставить комментарий",
      price: "Цена",
      total: "Итого",
      choosenProducts: "ВЫБРАННЫЕ ТОВАРЫ",
      products: "Товаров",
      Арзандатуу: "Скидка",
      makeOrder: "Оформить заказ",
      country: "Страна",
      city: "Город",
      address: "Адресс",
      shipping_method: "Способ доставки",
      pickUp: "Самовывоз",
      productsInOrder: "Товары в заказе",
      nothingInCart: "Ничего нет в корзине",
      watchInCalalog:
        "Вы можете найти товары в каталоге и добавить их в корзину чтобы потом выбрать их и сделать заказ.",
      fintInCatalog: "Найти товары в каталоге",
      deleteProduct: "Удалить товар??",
      deleteProductTxt: "Удалить выбранный товар из корзины?",
      no: "Нет",
      yes: "Да",
      successfullyOrdered: "Заказ успешно оформлен",
      successfullyOrderedTxt:
        "Ожидайте подтверждения заказа, проведения оплаты и доставки!",
      toOrders: "В заказы",
      descr: "Описание",
      noneProducts: "На складе больше нет товара",
      allOrders: "Всего заказов",
      onSum: "На сумму",
      changeAvatar: "Сменить фото профиля",
      changeProfileData: "Редактировать личные данные",
      changePassword: "Сменить пароль",
      orderDate: "Дата заказа",
      shippingDate: "Дата доставки",
      paymentMethod: "Способ оплаты",
      shippingMethod: "Способ доставки",
      productss: "Товаров",
      newOnesFirst: "Сперва новые",
      oldestFirst: "Сперва старые",
      chepOnesFirst: "Сперва дешевые",
      expensiveFirst: "Сперва дорогие",
      name: "Имя",
      phoneNumber: "Номер телефона",
      save: "Сохранить",
      settings: "Настройки профиля",
      password: "Пароль",
      enterNewPassword: "Введите новый пароль",
      repeatNewPassword: "Повторите новый пароль",
      default: "По умолчанию",
      enter: "Вход",
      toMain: "На главную",
      changePhone: "Смена номера телефона",
      change: "Сменить",
      fromNumber: "С номера",
      toNumber: "На номер",
      reg: "Регистрация",
      savee: "Запомнить",
      termsFirst: "Я принимаю",
      termsSecond: "условия соглашения",
      regg: "Зарегистрироваться",
      newPassword: "Востановить пароль",
      newPassword2:
        "Мы вышлем вам на номер телефона код подтверждения и ссылку для того чтобы вы могли пройдя по ссылке восстановить свой пароль.",
      newPasswordd: "Новый пароль",
      resetPassword: "Сбросить пароль",
      forgotPassword: "Забыл пароль",
      payment: "Оплата",
    },
  },
};

i18n
  .use(initReactI18next)
  .use(LanguageDetector)
  .init({
    supportedLngs: ["ru", "kg"],
    fallbackLng: "ru",
    detection: {
      order: ["path", "localStorage", "htmlTag", "subdomain"],
      caches: ["localStorage"],
    },
    resources,
  });

export default i18n;
